"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarClock, FileText, LoaderCircle, LockKeyhole, LogOut, Milestone, ShieldCheck, Upload } from "lucide-react";
import { API_URL, ApiError, apiFetch } from "@/lib/api";

type Portal = {
  team: { publicId:string; teamName:string; ventureName:string; collegeName:string; summary:string; pitchDeckUrl:string; prototypeUrl:string; leadEmail:string; stage:string; createdAt:string };
  members: Array<{ id:number; fullName:string; email:string; course:string; yearOfStudy:string; role:string; isLead:boolean }>;
  documents: Array<{ id:string; documentType:string; originalName:string; sizeBytes:number; status:string; createdAt:string }>;
  referrals: Array<{ id:string; referralType:string; providerName:string; status:string; nextAction:string; nextActionAt:string|null }>;
  milestones: Array<{ id:number; title:string; status:string; dueAt:string|null; evidenceUrl:string; notes:string }>;
  pitchSlots: Array<{ id:number; sessionTitle:string; sequenceNumber:number; startsAt:string; durationMinutes:number; room:string; status:string; result:string }>;
  canEdit:boolean;
};

const field="mt-2 h-12 w-full rounded-md border border-navy-900/15 bg-white px-4 text-sm outline-none focus:border-brand-orange focus:ring-2 focus:ring-brand-orange/10";

export function ApplicantPortal(){
  const [data,setData]=useState<Portal|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function load(){try{setData(await apiFetch<Portal>("/api/v1/launch-bharat/applicant/me"));}catch(error){if(!(error instanceof ApiError&&error.status===401))setMessage(error instanceof Error?error.message:"Could not load application");}finally{setLoading(false)}}
  useEffect(()=>{apiFetch<Portal>("/api/v1/launch-bharat/applicant/me").then(setData).catch(error=>{if(!(error instanceof ApiError&&error.status===401))setMessage(error instanceof Error?error.message:"Could not load application")}).finally(()=>setLoading(false))},[]);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{const raw=Object.fromEntries(new FormData(event.currentTarget).entries());await apiFetch("/api/v1/launch-bharat/applicant/login",{method:"POST",body:JSON.stringify(raw)});await load()}catch(error){setMessage(error instanceof Error?error.message:"Sign-in failed")}finally{setBusy(false)}}
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{await apiFetch("/api/v1/launch-bharat/applicant/documents",{method:"POST",body:new FormData(event.currentTarget)});event.currentTarget.reset();await load();setMessage("Document uploaded securely.")}catch(error){setMessage(error instanceof Error?error.message:"Upload failed")}finally{setBusy(false)}}
  async function password(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{await apiFetch("/api/v1/launch-bharat/applicant/password",{method:"PUT",body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget).entries()))});event.currentTarget.reset();setMessage("Password changed and other sessions signed out.")}catch(error){setMessage(error instanceof Error?error.message:"Password change failed")}finally{setBusy(false)}}
  async function logout(){await apiFetch("/api/v1/launch-bharat/applicant/logout",{method:"POST"}).catch(()=>undefined);setData(null)}
  if(loading)return <main className="grid min-h-screen place-items-center bg-[#f4f1e9]"><LoaderCircle className="size-6 animate-spin text-brand-orange"/></main>;
  if(!data)return <main className="min-h-screen bg-[#f4f1e9] px-4 py-16"><div className="mx-auto max-w-md"><Link href="/launch-bharat" className="inline-flex items-center gap-2 text-xs font-bold text-zinc-600"><ArrowLeft className="size-4"/>Back to programme</Link><section className="mt-8 border-t-4 border-brand-orange bg-white p-7 shadow-[0_20px_60px_rgba(7,11,22,.1)] sm:p-9"><p className="text-[10px] font-extrabold tracking-[.18em] text-brand-orange uppercase">Team access</p><h1 className="mt-4 font-heading text-3xl font-extrabold">Applicant portal</h1><p className="mt-3 text-sm leading-6 text-zinc-500">Track review status, upload evidence and manage your team’s application.</p>{message&&<Alert text={message}/>}<form onSubmit={login} className="mt-7 space-y-4"><Field name="applicationId" label="Application reference" placeholder="LB-…"/><Field name="email" label="Team lead email" type="email"/><Field name="password" label="Portal password" type="password"/><button disabled={busy} className="btn-accent h-12 w-full">{busy?<LoaderCircle className="size-4 animate-spin"/>:<LockKeyhole className="size-4"/>}Sign in securely</button></form><p className="mt-5 flex gap-2 text-[10px] leading-5 text-zinc-400"><ShieldCheck className="mt-0.5 size-3.5 shrink-0"/>Repeated failed attempts temporarily lock access. Contact programme operations if your credentials are unavailable.</p></section></div></main>;
  const stageIndex=["applied","eligible","shortlisted","finalist","incubating","launched"].indexOf(data.team.stage);
  return <main className="min-h-screen bg-[#f4f1e9]"><header className="border-b border-white/10 bg-navy-950 text-white"><div className="container-page flex min-h-20 items-center justify-between gap-4"><div><p className="text-[9px] font-bold tracking-[.18em] text-brand-orange uppercase">Launch Bharat · Applicant portal</p><p className="mt-1 text-sm font-extrabold">{data.team.ventureName} <span className="font-normal text-white/40">· {data.team.publicId}</span></p></div><button onClick={logout} className="flex items-center gap-2 text-xs font-bold text-white/60 hover:text-white"><LogOut className="size-4"/>Sign out</button></div></header><div className="container-page py-8 sm:py-12">
    {message&&<Alert text={message}/>}<section className="grid gap-6 border-t-4 border-brand-orange bg-white p-6 shadow-[0_12px_40px_rgba(7,11,22,.06)] lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-bold text-zinc-400 uppercase">{data.team.collegeName}</p><h1 className="mt-3 font-heading text-3xl font-extrabold">{data.team.teamName}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-600">{data.team.summary}</p></div><Status value={data.team.stage}/></section>
    <section className="mt-5 bg-navy-950 p-6 text-white"><p className="text-[9px] font-bold tracking-wider text-white/40 uppercase">Programme progression</p><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-6">{["Applied","Eligible","Shortlisted","Finalist","Incubating","Launched"].map((label,index)=><div key={label} className={`border-t-2 pt-3 text-[10px] font-bold ${index<=stageIndex?"border-brand-orange text-white":"border-white/15 text-white/30"}`}>{label}</div>)}</div></section>
    <div className="mt-5 grid items-start gap-5 xl:grid-cols-[1fr_380px]"><div className="space-y-5"><Panel title="Team members" icon={ShieldCheck}>{data.members.map(member=><div key={member.id} className="flex items-center justify-between border-t border-navy-900/8 py-4 first:border-0"><div><p className="text-sm font-bold">{member.fullName}</p><p className="mt-1 text-[10px] text-zinc-400">{member.email} · {member.course}, {member.yearOfStudy}</p></div><Status value={member.isLead?"team lead":member.role}/></div>)}</Panel><Panel title="Pitch schedule" icon={CalendarClock}>{data.pitchSlots.length?data.pitchSlots.map(slot=><div key={slot.id} className="border-t border-navy-900/8 py-4 first:border-0"><div className="flex justify-between gap-4"><div><p className="text-sm font-bold">{slot.sessionTitle}</p><p className="mt-1 text-xs text-zinc-500">{new Date(slot.startsAt).toLocaleString("en-IN")} · {slot.room||"Room pending"} · {slot.durationMinutes} min</p></div><Status value={slot.status}/></div></div>):<Empty text="Pitch allocation will appear here when scheduled."/>}</Panel><Panel title="Post-programme support" icon={Milestone}>{[...data.referrals,...data.milestones].length?<><div className="space-y-3">{data.referrals.map(item=><article key={item.id} className="border border-navy-900/10 p-4"><div className="flex justify-between"><strong className="text-sm">{item.providerName}</strong><Status value={item.status}/></div><p className="mt-2 text-xs text-zinc-500">{item.referralType.replaceAll("_"," ")} · {item.nextAction||"Next action pending"}</p></article>)}{data.milestones.map(item=><article key={item.id} className="border border-navy-900/10 p-4"><div className="flex justify-between"><strong className="text-sm">{item.title}</strong><Status value={item.status}/></div><p className="mt-2 text-xs text-zinc-500">{item.dueAt?`Due ${new Date(item.dueAt).toLocaleDateString("en-IN")}`:"No due date"}</p></article>)}</div></>:<Empty text="Mentor, incubator and milestone follow-through will be recorded here."/>}</Panel></div>
    <aside className="space-y-5"><Panel title="Documents" icon={FileText}><form onSubmit={upload} className="space-y-3"><select name="documentType" className={field}><option value="pitch_deck">Pitch deck (PDF)</option><option value="prototype_evidence">Prototype evidence</option><option value="identity_proof">Identity proof</option><option value="college_authorization">College authorization</option><option value="other">Other</option></select><input required name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" className="block w-full text-xs file:mr-3 file:border-0 file:bg-navy-950 file:px-4 file:py-3 file:text-xs file:font-bold file:text-white"/><button disabled={busy} className="btn-primary h-11 w-full"><Upload className="size-4"/>Upload document</button></form><div className="mt-5 divide-y divide-navy-900/8">{data.documents.map(doc=><a key={doc.id} href={`${API_URL}/api/v1/launch-bharat/applicant/documents/${doc.id}`} className="block py-3 text-xs font-bold hover:text-brand-orange">{doc.originalName}<span className="mt-1 block text-[9px] font-normal text-zinc-400">{doc.documentType.replaceAll("_"," ")} · {(doc.sizeBytes/1024).toFixed(0)} KB</span></a>)}</div></Panel><Panel title="Account security" icon={LockKeyhole}><form onSubmit={password} className="space-y-3"><Field name="currentPassword" label="Current password" type="password"/><Field name="newPassword" label="New password" type="password"/><button disabled={busy} className="h-11 w-full rounded-md border border-navy-900/15 text-xs font-bold hover:bg-zinc-50">Change password</button></form></Panel></aside></div>
  </div></main>;
}
function Panel({title,icon:Icon,children}:{title:string;icon:typeof ShieldCheck;children:React.ReactNode}){return <section className="border border-navy-900/10 bg-white"><div className="flex items-center gap-3 border-b border-navy-900/8 p-5"><Icon className="size-4 text-brand-orange"/><h2 className="text-sm font-extrabold">{title}</h2></div><div className="p-5">{children}</div></section>}
function Field({name,label,type="text",placeholder}:{name:string;label:string;type?:string;placeholder?:string}){return <label className="block"><span className="text-[9px] font-bold tracking-wide text-zinc-500 uppercase">{label}</span><input required name={name} type={type} placeholder={placeholder} minLength={type==="password"?10:undefined} className={field}/></label>}
function Status({value}:{value:string}){return <span className="inline-flex h-fit rounded-full bg-orange-50 px-2.5 py-1 text-[8px] font-extrabold tracking-wide text-orange-700 uppercase">{value.replaceAll("_"," ")}</span>}
function Empty({text}:{text:string}){return <p className="py-5 text-center text-xs leading-6 text-zinc-400">{text}</p>}
function Alert({text}:{text:string}){return <p role="status" className="mt-5 border border-orange-200 bg-orange-50 p-3 text-xs text-orange-800">{text}</p>}
