import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, QrCode, Search, TicketCheck } from "lucide-react";
import { PageHero } from "@/components/marketing/PageHero";
import { Section } from "@/components/marketing/Section";

export const metadata:Metadata={title:"For Students",description:"Find college events, register free and receive a verified QR pass."};

export default function ForStudentsPage(){const steps=[[Search,"Find your campus","Search by college, university, city or state."],[TicketCheck,"Choose an event","Read the verified schedule, venue, organizer and capacity."],[CheckCircle2,"Register free","Enter your student details. No payment is required right now."],[QrCode,"Show your QR","Keep the pass on your phone and present it at the entrance."]];return <><PageHero eyebrow="For students" title={<>Less searching.<br/><span className="text-brand-orange">More showing up.</span></>} description="Discover what is happening at your college and reserve a free, verified event pass without chasing forms across group chats." primaryHref="/colleges" primaryLabel="Find my college" secondaryHref="/events" secondaryLabel="Browse all events"/><Section eyebrow="How it works" title="From search to entry in four clear steps."><div className="grid gap-4 md:grid-cols-4">{steps.map(([Icon,title,copy],index)=>{const Mark=Icon as typeof Search;return <article key={String(title)} className="rounded-md border border-navy-900/12 bg-[#fffdf8] p-6"><div className="flex items-center justify-between"><Mark className="size-5 text-brand-orange"/><span className="font-mono text-xs text-zinc-300">0{index+1}</span></div><h2 className="mt-10 font-bold">{String(title)}</h2><p className="mt-3 text-sm leading-relaxed text-zinc-500">{String(copy)}</p></article>})}</div></Section><Section variant="dark" title="Your pass belongs to you." lead="The QR contains an unguessable pass identifier. Your full contact details are visible only to the authorised event team."><Link href="/events" className="btn-accent">Find an event</Link></Section></>}
