import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, QrCode, Search, TicketCheck } from "lucide-react";
import { PageHero } from "@/components/marketing/PageHero";
import { Section } from "@/components/marketing/Section";

export const metadata:Metadata={title:"For Students",description:"Find college events, register free and receive a verified QR pass."};

export default function ForStudentsPage(){const steps=[[Search,"Find an institution","Search by college, university, city or state."],[TicketCheck,"Review an event","Check the published schedule, venue, organizer and availability."],[CheckCircle2,"Complete registration","Provide the attendee information required for the event."],[QrCode,"Present the QR pass","Keep the confirmed pass on your phone and show it at the entrance."]];return <><PageHero eyebrow="For students" title={<>Find and register for <span className="text-brand-orange">college events.</span></>} description="Use one directory to find your institution, review published events and receive a verified QR pass after registration." primaryHref="/colleges" primaryLabel="Find an institution" secondaryHref="/events" secondaryLabel="View events"/><Section eyebrow="Registration process" title="Four steps from discovery to entry"><div className="grid border-y border-navy-900/12 md:grid-cols-4">{steps.map(([Icon,title,copy],index)=>{const Mark=Icon as typeof Search;return <article key={String(title)} className="border-b border-navy-900/12 p-6 md:border-b-0 md:border-r md:last:border-r-0"><div className="flex items-center justify-between"><Mark className="size-5 text-brand-orange"/><span className="font-mono text-xs text-zinc-300">0{index+1}</span></div><h2 className="mt-10 font-bold">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{String(copy)}</p></article>})}</div></Section><Section variant="dark" title="Secure event passes" lead="Each QR code contains a random pass identifier rather than the attendee's personal details. Contact information is available only to authorized event staff."><Link href="/events" className="btn-accent">View events</Link></Section></>}
