import type { Metadata } from "next";
import Link from "next/link";
import { Building2, CalendarCheck2, QrCode, ShieldCheck } from "lucide-react";
import { PageHero } from "@/components/marketing/PageHero";
import { Section } from "@/components/marketing/Section";

export const metadata:Metadata={title:"About",description:"Why EventWallah is building a simpler college-event network for India."};

export default function AboutPage(){const principles=[[Building2,"Campus-first","Events are organised around the institution students already know."],[CalendarCheck2,"Current information","College teams publish updates directly, giving students one reliable listing."],[QrCode,"Simple entry","Every confirmed registration receives one secure, scannable pass."],[ShieldCheck,"Responsible data","QR codes contain a random pass reference rather than personal details."]];return <><PageHero eyebrow="About EventWallah" title={<>A clearer way to find and attend <span className="text-brand-orange">college events.</span></>} description="College events are often scattered across posters, group chats and social feeds. EventWallah gives each institution a searchable calendar and each attendee a verifiable pass." primaryHref="/events" primaryLabel="Explore events" secondaryHref="/colleges" secondaryLabel="Find a college"/><Section eyebrow="What we are building" title="One dependable layer between campuses and students." lead="The platform is designed for festivals, workshops, hackathons, competitions, cultural programmes and every other event a college team needs to publish."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{principles.map(([Icon,title,copy])=>{const Mark=Icon as typeof Building2;return <article key={String(title)} className="rounded-md border border-navy-900/12 bg-[#fffdf8] p-6"><Mark className="size-5 text-brand-orange"/><h2 className="mt-8 font-bold">{String(title)}</h2><p className="mt-3 text-sm leading-relaxed text-zinc-500">{String(copy)}</p></article>})}</div></Section><Section variant="dark" title="Built for a national directory, operated institution by institution." lead="EventWallah supports reviewed institution data and secure event publishing for participating campuses."><Link href="/contact" className="btn-accent">List events from your institution</Link></Section></>}
