"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDownRight, ArrowUpRight, Banknote, LoaderCircle, Plus, ReceiptText, WalletCards } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminShell";
import { apiFetch, authHeaders, formatMoney, type Event, type FinanceSummary } from "@/lib/api";

type Expense={id:number;eventId:number|null;eventTitle:string;category:string;vendorName:string;description:string;amountPaise:number;taxPaise:number;paymentStatus:string;incurredAt:string;createdAt:string};
const empty:FinanceSummary={ticketGrossPaise:0,ticketDiscountPaise:0,ticketCollectedPaise:0,sponsorContractedPaise:0,sponsorReceivedPaise:0,sponsorOutstandingPaise:0,expensesPaise:0,netPositionPaise:0};

export function FinanceWorkspace(){const router=useRouter();const [summary,setSummary]=useState(empty);const [expenses,setExpenses]=useState<Expense[]>([]);const [events,setEvents]=useState<Event[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function load(){try{const headers=authHeaders();const [financeData,expenseData,eventData]=await Promise.all([apiFetch<FinanceSummary>("/api/v1/admin/finance",{headers}),apiFetch<{items:Expense[]}>("/api/v1/admin/expenses",{headers}),apiFetch<{items:Event[]}>("/api/v1/admin/events",{headers})]);setSummary(financeData);setExpenses(expenseData.items);setEvents(eventData.items)}catch(caught){if((caught as {status?:number}).status===401)router.replace("/admin/login");else setError(caught instanceof Error?caught.message:"Could not load finance workspace")}}useEffect(()=>{const headers=authHeaders();Promise.all([apiFetch<FinanceSummary>("/api/v1/admin/finance",{headers}),apiFetch<{items:Expense[]}>("/api/v1/admin/expenses",{headers}),apiFetch<{items:Event[]}>("/api/v1/admin/events",{headers})]).then(([financeData,expenseData,eventData])=>{setSummary(financeData);setExpenses(expenseData.items);setEvents(eventData.items)}).catch(caught=>{if((caught as {status?:number}).status===401)router.replace("/admin/login");else setError(caught instanceof Error?caught.message:"Could not load finance workspace")})},[router]);
 async function createExpense(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const raw=Object.fromEntries(new FormData(form).entries());const body={eventId:raw.eventId?Number(raw.eventId):null,category:raw.category,vendorName:raw.vendorName,description:raw.description,amountPaise:Math.round(Number(raw.amountRupees)*100),taxPaise:Math.round(Number(raw.taxRupees||0)*100),paymentStatus:raw.paymentStatus,incurredAt:new Date(String(raw.incurredAt)).toISOString()};setBusy(true);setError("");try{await apiFetch("/api/v1/admin/expenses",{method:"POST",headers:authHeaders(),body:JSON.stringify(body)});form.reset();await load()}catch(caught){setError(caught instanceof Error?caught.message:"Could not record expense")}finally{setBusy(false)}}
 const income=summary.ticketCollectedPaise+summary.sponsorReceivedPaise;const sponsorShare=income?Math.round(summary.sponsorReceivedPaise/income*100):0;const ticketShare=income?100-sponsorShare:0;
 return <AdminShell><div><p className="text-[10px] font-bold tracking-[.17em] text-zinc-400 uppercase">Financial control</p><h2 className="mt-2 font-heading text-2xl font-extrabold tracking-tight sm:text-3xl">Event finance ledger</h2><p className="mt-2 text-xs text-zinc-500">Ticket income, sponsorship collections, expenses and current net position.</p></div>{error&&<p className="mt-5 rounded-md border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}
 <div className="mt-7 grid grid-cols-2 gap-3 xl:grid-cols-4">{[["Cash collected",formatMoney(income),ArrowUpRight,"text-emerald-600","bg-emerald-50"],["Outstanding sponsors",formatMoney(summary.sponsorOutstandingPaise),WalletCards,"text-amber-600","bg-amber-50"],["Recorded expenses",formatMoney(summary.expensesPaise),ArrowDownRight,"text-red-600","bg-red-50"],["Net position",formatMoney(summary.netPositionPaise),Banknote,summary.netPositionPaise>=0?"text-blue-600":"text-red-600","bg-blue-50"]].map(([label,value,Icon,color,bg])=>{const Mark=Icon as typeof Banknote;return <article key={String(label)} className="rounded-md border border-navy-900/10 bg-white p-5"><span className={`flex size-9 items-center justify-center rounded-md ${bg}`}><Mark className={`size-4 ${color}`}/></span><p className="mt-6 text-[9px] font-bold text-zinc-400 uppercase">{String(label)}</p><p className="mt-2 text-xl font-extrabold sm:text-2xl">{String(value)}</p></article>})}</div>
 <div className="mt-5 grid items-start gap-5 xl:grid-cols-[1fr_380px]"><div className="space-y-5"><section className="rounded-md border border-navy-900/10 bg-white"><SectionHead title="Income composition" detail="Confirmed collections by commercial channel"/><div className="p-5 pt-0"><div className="flex h-4 overflow-hidden rounded-full bg-zinc-100"><div className="bg-brand-orange" style={{width:`${ticketShare}%`}}/><div className="bg-navy-950" style={{width:`${sponsorShare}%`}}/></div><div className="mt-5 grid grid-cols-2 gap-4"><MoneyLine color="bg-brand-orange" label="Ticket collections" value={summary.ticketCollectedPaise} detail={`${ticketShare}% of received income`}/><MoneyLine color="bg-navy-950" label="Sponsor collections" value={summary.sponsorReceivedPaise} detail={`${sponsorShare}% of received income`}/></div><div className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-md bg-navy-900/8 ring-1 ring-navy-900/8"><div className="bg-zinc-50 p-4"><p className="text-[9px] text-zinc-400 uppercase">Gross ticket value</p><p className="mt-2 font-bold">{formatMoney(summary.ticketGrossPaise)}</p></div><div className="bg-zinc-50 p-4"><p className="text-[9px] text-zinc-400 uppercase">Discounts funded</p><p className="mt-2 font-bold">{formatMoney(summary.ticketDiscountPaise)}</p></div></div></div></section>
 <section className="overflow-hidden rounded-md border border-navy-900/10 bg-white"><SectionHead title="Expense register" detail="Vendor costs, tax and approval state"/><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-zinc-50 text-[9px] font-bold text-zinc-400 uppercase"><tr><th className="px-5 py-3">Vendor</th><th className="px-5 py-3">Event</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{expenses.map((item)=><tr key={item.id} className="border-t border-navy-900/7"><td className="px-5 py-4"><strong>{item.vendorName}</strong><span className="mt-1 block text-[9px] text-zinc-400">{new Date(item.incurredAt).toLocaleDateString("en-IN")}</span></td><td className="px-5 py-4 text-zinc-600">{item.eventTitle}</td><td className="px-5 py-4">{item.category}</td><td className="px-5 py-4 font-extrabold">{formatMoney(item.amountPaise+item.taxPaise)}<span className="mt-1 block text-[9px] font-normal text-zinc-400">Tax {formatMoney(item.taxPaise)}</span></td><td className="px-5 py-4"><span className="rounded-full bg-zinc-100 px-2 py-1 text-[9px] font-bold uppercase">{item.paymentStatus}</span></td></tr>)}</tbody></table>{!expenses.length&&<div className="py-14 text-center"><ReceiptText className="mx-auto size-6 text-zinc-300"/><p className="mt-3 text-xs text-zinc-400">No expenses recorded.</p></div>}</div></section></div>
 <form onSubmit={createExpense} className="rounded-md border border-navy-900/10 bg-white xl:sticky xl:top-[100px]"><SectionHead title="Record expense" detail="Add a controlled vendor cost"/><div className="space-y-4 border-t border-navy-900/8 p-5"><Select name="eventId" label="Event"><option value="">Organization level</option>{events.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</Select><Input name="vendorName" label="Vendor"/><Input name="category" label="Category" placeholder="Production, venue, catering…"/><Input name="description" label="Description" required={false}/><div className="grid grid-cols-2 gap-3"><Input name="amountRupees" label="Amount (₹)" type="number" min="0"/><Input name="taxRupees" label="Tax (₹)" type="number" min="0" defaultValue="0"/></div><Select name="paymentStatus" label="Payment status"><option value="pending">Pending</option><option value="approved">Approved</option><option value="paid">Paid</option></Select><Input name="incurredAt" label="Incurred at" type="datetime-local"/><button disabled={busy} className="btn-accent h-11 w-full">{busy?<LoaderCircle className="size-4 animate-spin"/>:<Plus className="size-4"/>}Record expense</button></div></form></div>
 </AdminShell>}
function SectionHead({title,detail}:{title:string;detail:string}){return <div className="p-5"><h3 className="text-sm font-extrabold">{title}</h3><p className="mt-1 text-[10px] text-zinc-400">{detail}</p></div>}
function MoneyLine({color,label,value,detail}:{color:string;label:string;value:number;detail:string}){return <div className="flex gap-3"><span className={`mt-1 size-2 rounded-full ${color}`}/><div><p className="text-[10px] font-bold">{label}</p><p className="mt-1 text-lg font-extrabold">{formatMoney(value)}</p><p className="mt-1 text-[9px] text-zinc-400">{detail}</p></div></div>}
function Input({name,label,type="text",required=true,placeholder,min,defaultValue}:{name:string;label:string;type?:string;required?:boolean;placeholder?:string;min?:string;defaultValue?:string}){return <label className="block"><span className="text-[9px] font-bold text-zinc-500 uppercase">{label}</span><input name={name} type={type} required={required} placeholder={placeholder} min={min} defaultValue={defaultValue} className="admin-input"/></label>}
function Select({name,label,children}:{name:string;label:string;children:React.ReactNode}){return <label className="block"><span className="text-[9px] font-bold text-zinc-500 uppercase">{label}</span><select name={name} className="admin-input">{children}</select></label>}
