/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, Download, MapPin, ShieldAlert, TicketCheck } from "lucide-react";
import { API_URL, apiFetch, formatEventDate, formatEventTime, type Pass, type Registration } from "@/lib/api";

export function PassView({token}:{token:string}){
 const [pass,setPass]=useState<Pass|null>(null); const [error,setError]=useState("");
 useEffect(()=>{apiFetch<Pass>(`/api/v1/passes/${token}`).then(setPass).catch((caught)=>{const cached=sessionStorage.getItem(`eventwallah_pass_${token}`);if(cached){const item=JSON.parse(cached) as Registration;setPass({publicId:item.publicId,fullName:item.fullName,studentCollege:item.collegeName,course:item.course,yearOfStudy:item.yearOfStudy,status:item.status,checkedInAt:item.checkedInAt,eventSlug:item.eventSlug??"",eventTitle:item.eventTitle,startsAt:"",venue:"",hostCollege:"",qrUrl:item.qrUrl});}else setError(caught instanceof Error?caught.message:"Pass not found")});},[token]);
 if(error)return <div className="container-narrow py-24 text-center"><ShieldAlert className="mx-auto size-10 text-red-500"/><h1 className="mt-5 text-3xl font-bold">Pass unavailable</h1><p className="mt-3 text-zinc-500">{error}</p><Link href="/events" className="btn-primary mt-7">Browse events</Link></div>;
 if(!pass)return <div className="container-narrow py-24 text-center">Loading your pass…</div>;
 const qrSrc=`${API_URL}${pass.qrUrl}`; const checkedIn=pass.status==="checked_in";
 return <div className="min-h-[75vh] bg-[#f2efe7] py-12 sm:py-20"><div className="container-narrow"><div className="text-center">{checkedIn?<CheckCircle2 className="mx-auto size-10 text-emerald-600"/>:<TicketCheck className="mx-auto size-10 text-brand-orange"/>}<p className="mt-4 eyebrow">{checkedIn?"Check-in complete":"Registration confirmed"}</p><h1 className="mt-5 font-heading text-3xl font-extrabold sm:text-4xl">{checkedIn?"You are checked in.":"Your pass is ready."}</h1><p className="mt-3 text-sm text-zinc-500">Keep this page or save the QR before you leave.</p></div><article className="mt-9 overflow-hidden rounded-md border border-navy-900/15 bg-[#fffdf8] shadow-[var(--shadow-card)]"><div className="bg-navy-950 p-6 text-white sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.16em] text-brand-orange uppercase">EventWallah pass</p><h2 className="mt-4 max-w-md text-2xl font-bold text-white">{pass.eventTitle}</h2><p className="mt-2 text-sm text-white/45">{pass.hostCollege}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase ${checkedIn?"bg-emerald-400/15 text-emerald-300":"bg-white/10 text-white/60"}`}>{pass.status.replace("_"," ")}</span></div></div><div className="grid md:grid-cols-[1fr_250px]"><div className="p-6 sm:p-8"><p className="text-[10px] font-bold tracking-wider text-zinc-400 uppercase">Pass holder</p><p className="mt-2 text-xl font-bold">{pass.fullName}</p><p className="mt-1 text-sm text-zinc-500">{pass.course} · {pass.yearOfStudy}</p><p className="text-sm text-zinc-500">{pass.studentCollege}</p>{pass.startsAt&&<div className="mt-7 space-y-3 border-t border-navy-900/10 pt-6 text-sm text-zinc-600"><p className="flex items-center gap-3"><CalendarDays className="size-4 text-brand-orange"/>{formatEventDate(pass.startsAt,true)}</p><p className="flex items-center gap-3"><Clock3 className="size-4 text-brand-orange"/>{formatEventTime(pass.startsAt)}</p><p className="flex items-center gap-3"><MapPin className="size-4 text-brand-orange"/>{pass.venue}</p></div>}<div className="mt-8"><p className="text-[10px] font-bold tracking-wider text-zinc-400 uppercase">Pass ID</p><p className="mt-1 font-mono text-sm font-bold">{pass.publicId}</p></div></div><div className="flex flex-col items-center justify-center border-t border-dashed border-navy-900/20 bg-white p-6 md:border-l md:border-t-0"><img src={qrSrc} alt={`QR pass ${pass.publicId}`} width={190} height={190} className="size-[190px]"/><p className="mt-3 text-center text-[10px] font-semibold text-zinc-400">Present this QR at the event entrance</p><a href={qrSrc} download={`${pass.publicId}.png`} className="btn-secondary-light mt-4 h-9 text-xs"><Download className="size-3.5"/>Save QR</a></div></div></article><p className="mt-5 text-center text-xs text-zinc-400">This pass is unique to you. Do not share it publicly.</p></div></div>;
}
