import type { College, Event } from "@/lib/api";

export const demoColleges: College[] = [
  { id: 1, slug: "indian-institute-of-technology-bombay", name: "Indian Institute of Technology Bombay", shortName: "IIT Bombay", institutionType: "college", ownership: "government", city: "Mumbai", state: "Maharashtra", website: "https://www.iitb.ac.in", logoUrl: "", eventCount: 1 },
  { id: 2, slug: "university-of-delhi", name: "University of Delhi", shortName: "DU", institutionType: "university", ownership: "government", city: "New Delhi", state: "Delhi", website: "https://www.du.ac.in", logoUrl: "", eventCount: 1 },
  { id: 3, slug: "christ-university-bengaluru", name: "CHRIST (Deemed to be University)", shortName: "CHRIST", institutionType: "university", ownership: "deemed", city: "Bengaluru", state: "Karnataka", website: "https://christuniversity.in", logoUrl: "", eventCount: 1 },
  { id: 5, slug: "vellore-institute-of-technology", name: "Vellore Institute of Technology", shortName: "VIT", institutionType: "university", ownership: "private", city: "Vellore", state: "Tamil Nadu", website: "https://vit.ac.in", logoUrl: "", eventCount: 1 },
];

export const demoEvents: Event[] = [
  { id: 1, collegeId: 1, collegeSlug: demoColleges[0].slug, collegeName: demoColleges[0].name, collegeCity: "Mumbai", slug: "techfest-open-house-2026", title: "Techfest Open House 2026", category: "Technology", summary: "An evening of student prototypes, robotics demonstrations and open labs.", description: "Meet student technical teams, explore working prototypes and attend short demonstrations across the institute's innovation spaces.", venue: "Students' Activity Centre", startsAt: "2026-09-12T10:00:00+05:30", endsAt: "2026-09-12T18:00:00+05:30", registrationDeadline: "2026-09-10T23:59:00+05:30", capacity: 600, status: "published", bannerUrl: "", organizerName: "Techfest Student Team", contactEmail: "events@iitb.ac.in", registrationCount: 0 },
  { id: 2, collegeId: 2, collegeSlug: demoColleges[1].slug, collegeName: demoColleges[1].name, collegeCity: "New Delhi", slug: "north-campus-cultural-evening", title: "North Campus Cultural Evening", category: "Culture", summary: "Music, theatre and dance performances from societies across North Campus.", description: "A student-led cultural programme featuring selected performances from participating colleges, followed by an informal society meet-up.", venue: "University Stadium Conference Centre", startsAt: "2026-09-20T16:00:00+05:30", endsAt: "2026-09-20T21:00:00+05:30", registrationDeadline: "2026-09-18T18:00:00+05:30", capacity: 450, status: "published", bannerUrl: "", organizerName: "DU Cultural Council", contactEmail: "culture@du.ac.in", registrationCount: 0 },
  { id: 3, collegeId: 3, collegeSlug: demoColleges[2].slug, collegeName: demoColleges[2].name, collegeCity: "Bengaluru", slug: "campus-founder-meet-2026", title: "Campus Founder Meet", category: "Entrepreneurship", summary: "A practical meet-up for student founders, builders and campus incubator teams.", description: "Short founder sessions, product feedback tables and office hours with operators from Bengaluru's startup community.", venue: "KE Auditorium, Central Campus", startsAt: "2026-10-03T09:30:00+05:30", endsAt: "2026-10-03T17:00:00+05:30", registrationDeadline: "2026-09-30T23:59:00+05:30", capacity: 300, status: "published", bannerUrl: "", organizerName: "Innovation and Incubation Centre", contactEmail: "innovation@christuniversity.in", registrationCount: 0 },
  { id: 4, collegeId: 5, collegeSlug: demoColleges[3].slug, collegeName: demoColleges[3].name, collegeCity: "Vellore", slug: "design-code-sprint", title: "Design × Code Sprint", category: "Hackathon", summary: "A one-day team sprint to prototype useful tools for campus life.", description: "Multidisciplinary teams will choose a campus problem, validate it with users and present a working prototype to the review panel.", venue: "Anna Auditorium", startsAt: "2026-10-10T08:00:00+05:30", endsAt: "2026-10-10T20:00:00+05:30", registrationDeadline: "2026-10-06T23:59:00+05:30", capacity: 240, status: "published", bannerUrl: "", organizerName: "VIT Technology Club", contactEmail: "clubs@vit.ac.in", registrationCount: 0 },
];
